spring:
  cloud:
    alicloud:
      access-key: *************************
      secret-key: *************************
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
    nacos:
      discovery:
        server-addr: 118.178.91.236:8848
        weight: 0.75
server:
  port: 30001

#management:
#  endpoint:
#    web:
#      expsoure:
#        include: '*'
