spring:
  datasource:
    username: root01
    password: 123456
    url: jdbc:mysql://118.178.91.236:3306/leave_users?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000

  cloud:
    nacos:
      discovery:
        server-addr: 118.178.91.236:8848

  application:
    name: leave-users
  jackson:
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 13000

